jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Clear npm cache
        run: npm cache clean --force
        working-directory: ./trustasitter-frontend

      - name: Clean install state
        run: |
          rm -rf node_modules package-lock.json
        working-directory: ./trustasitter-frontend

      - name: Install dependencies
        run: npm install
        working-directory: ./trustasitter-frontend

      - name: Run build
        run: npm run build
        working-directory: ./trustasitter-frontend
