name: CI - Backend

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install
        working-directory: ./

      - name: Check server startup
        run: npm run start &
        working-directory: ./

      - name: Wait for server to respond
        run: sleep 5

      - name: Stop server
        run: pkill node || true
